import Head from 'next/head'
import React from 'react'
import Header from './header'

const Layout = ({ children }) => {
  return (
    <>
    <Head>
        <title>amazon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    {children}
    </>
  )
}

export default Layout